FROM ubuntu:24.04

ARG RELEASE_VERSION=""
ARG TCAMAKE_VERSION=v25.08.20
ARG TDH_UID=1001
ARG TDH_GID=${TDH_UID}

LABEL org.opencontainers.image.authors="Timothy C. Arland <tcarland at gmail dot com>" \
      org.opencontainers.image.base.name="ubuntu:24.04" \
      org.opencontainers.image.description="tcanetpp build container" \
      org.opencontainers.image.source="https://github.com/tcarland/tcanetpp" \
      org.opencontainers.image.title="tcanetpp" \
      org.opencontainers.image.version="${RELEASE_VERSION}"

ENV HOME=/root
ENV TCAMAKE_HOME=/opt/tcamake

RUN apt-get update && apt-get -y --no-install-recommends install \
    bash \
    build-essential \
    ca-certificates \
    curl \
    libtool \
    liblz4-dev \
    libssl-dev \
    libxml2-dev \
    libzstd-dev \
    net-tools \
    pkg-config \
    rsync \
    tini && \
    apt-get clean

SHELL ["/bin/bash", "-c"]

WORKDIR /opt

COPY . /opt/tcanetpp
COPY ca.cr[t] /opt/

RUN if [ -f ca.crt ]; then \
        cp ca.crt /usr/local/share/ca-certificates/tcanet-ca.crt && \
        update-ca-certificates; \
    fi

RUN groupadd --gid ${TDH_GID} tdh && \
    useradd -m -u ${TDH_UID} -g ${TDH_GID} tdh && \
    chown -R tdh:tdh /opt/tcanetpp && \
    curl https://github.com/tcarland/tcamake/archive/refs/tags/${TCAMAKE_VERSION}.tar.gz -L -o /tmp/tcamake.tar.gz && \
    tar -xzf /tmp/tcamake.tar.gz && \
    mv tcamake-* tcamake && \
    rm /tmp/tcamake.tar.gz

RUN cd tcanetpp && \
    source resources/release_mt.env && \
    make arlib cmdbuf && \
    make install && \
    make distclean

USER tdh

ENTRYPOINT [ "/usr/bin/tini", "--" ]
CMD [ "/bin/bash" ]
