# tcanetpp Containerfile
# 
# This creates a base image for collecting/building a suite of 
# tools from the tcalib collection that are collectively 
# called 'tcalibcore'.
# 
FROM debian:12.12-slim
ARG RELEASE_VERSION=""

ARG TDH_UID=1001
ARG TDH_GID=${TDH_UID}

ARG tcamake_uri="https://github.com/tcarland/tcamake/archive/refs/tags"
ARG tcamake_version="25.10.10"  # note the dropped 'v' for pathing issues

LABEL org.opencontainers.image.authors="Timothy C. Arland <tcarland at gmail dot com>" \
      org.opencontainers.image.base.name="debian:12.12-slim" \
      org.opencontainers.image.description="tcanetpp build container" \
      org.opencontainers.image.source="https://github.com/tcarland/tcanetpp" \
      org.opencontainers.image.title="tcanetpp" \
      org.opencontainers.image.version="${RELEASE_VERSION}"

SHELL ["/bin/bash", "-c"]

COPY . /opt/tcanetpp

RUN apt-get update && apt-get -y --no-install-recommends install \
    bash \
    build-essential \
    ca-certificates \
    curl \
    libtool \
    liblz4-dev \
    libssl-dev \
    libxml2-dev \
    libzstd-dev \
    net-tools \
    pkg-config \
    rsync \
    tini && \
    apt-get clean && \
    groupadd --gid ${TDH_GID} tdh && \
    useradd -m -u ${TDH_UID} -g ${TDH_GID} tdh && \
    chown -R tdh:tdh /opt/tcanetpp

WORKDIR /opt

COPY ca.cr[t] /opt/
RUN if [ -f ca.crt ]; then \
        cp ca.crt /usr/local/share/ca-certificates/tcanet-ca.crt && \
        update-ca-certificates; \
    fi

RUN curl -L ${tcamake_uri}/v${tcamake_version}.tar.gz -o /tmp/tcamake.tar.gz && \
    tar -xzf /tmp/tcamake.tar.gz -C /opt && \
    ln -s tcamake-${tcamake_version} tcamake && \
    rm /tmp/tcamake.tar.gz

RUN cd tcanetpp && \
    source resources/release_mt.env && \
    make arlib cmdbuf && \
    make install && \
    make clean

USER tdh

ENV TCAMAKE_HOME=/opt/tcamake

ENTRYPOINT [ "/usr/bin/tini", "--" ]
CMD [ "/bin/bash" ]
