FROM ubuntu:24.04

LABEL description="cpp container build"
LABEL author="Timothy C. Arland <tcarland at gmail dot com>"

ARG TCAMAKE_VERSION=v25.01.28

ENV HOME=/root
ENV TCAMAKE_HOME=/opt/tcamake
ENV TCAMAKE_PREFIX=/usr

RUN apt-get update && apt-get -y --no-install-recommends install \
    bash \
    build-essential \
    ca-certificates \
    curl \
    libtool \
    liblz4-dev \
    libssl-dev \
    libxml2-dev \
    libzstd-dev \
    net-tools \
    pkg-config \
    tini 

SHELL ["/bin/bash", "-c"]

WORKDIR /opt

COPY . /opt/tcanetpp

RUN useradd -m --uid 1001 tdh && \
    chown -R tdh:tdh /opt/tcanetpp && \
    curl https://github.com/tcarland/tcamake/archive/refs/tags/${TCAMAKE_VERSION}.tar.gz -L -o /tmp/tcamake.tar.gz && \
    tar -xzf /tmp/tcamake.tar.gz && \
    mv tcamake-* tcamake && \
    rm /tmp/tcamake.tar.gz

RUN cd tcanetpp && source resources/release_mt.env && \
    make arlib cmdbuf && make install && make distclean

USER tdh

ENTRYPOINT ["/usr/bin/tini", "--"]
